#!/bin/bash
#cabal install --overwrite-policy=always --installdir=dist-newstyle compiler

./dist-newstyle/compiler examples/test-moj.ins llvm > playground/foo.ll

cd playground
llvm-as foo.ll
llvm-link -o out.bc foo.bc runtime.bc
lli out.bc