#!/bin/bash
DIRNAME=`dirname $1`
BASENAME=`basename $1 .ins`
JASMIN="$DIRNAME/${BASENAME}.j"
./dist-newstyle/compiler "$1" jvm > $JASMIN
var=".class public ${BASENAME}"
sed -i "1s/.*/$var/" $JASMIN
java -jar lib/jasmin.jar -d $DIRNAME "$DIRNAME/$BASENAME.j"