#!/bin/bash
# lli out.bc

DIRNAME=`dirname $1`
BASENAME=`basename $1 .ins`
LLVM="$DIRNAME/${BASENAME}.ll"
LLVMBC="$DIRNAME/${BASENAME}.bc"
./dist-newstyle/compiler "$1" llvm > $LLVM
llvm-as $LLVM
llvm-link -o $LLVMBC $LLVMBC lib/runtime.bc




